name: Test & Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"  # Trigger on version tags like v2025.7.8

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Run Tests
        run: |
          poetry run pytest --maxfail=1 --disable-warnings -v

      - name: Build and publish to PyPI
        run: |
          poetry config pypi-token.pypi ""
          poetry publish --build
